2023-12-10 16:19:22,262 | ERROR | invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\2.7\server.py", line 77, in main
    user_input = protocol.deformat_message(client_socket)
  File "D:\Python\Networks with Nir\2.7\protocol.py", line 46, in deformat_message
    length = (length * 10) + int(char)
ValueError: invalid literal for int() with base 10: ''
2023-12-10 16:19:31,144 | ERROR | 'Server' object has no attribute 'client_socket'
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\2.7\server.py", line 82, in main
    server.send_message(client_socket, getattr(server_functions, user_input[0].decode()).__call__())
  File "D:\Python\Networks with Nir\2.7\server.py", line 55, in send_message
    self.client_socket.send(protocol.format_message(msg))
AttributeError: 'Server' object has no attribute 'client_socket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Networks with Nir\2.7\server.py", line 88, in main
    server.send_message(client_socket, "False " + str(err))
  File "D:\Python\Networks with Nir\2.7\server.py", line 55, in send_message
    self.client_socket.send(protocol.format_message(msg))
AttributeError: 'Server' object has no attribute 'client_socket'
